version: '3.5'

services:
  # MySQL database for springboot app
  db_mysql:
    container_name: 'deployment_db_mysql'
    image: mysql:5.7    
    environment:      
      MYSQL_DATABASE: 'db_spring'              
      MYSQL_USER: 'user'      
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3366
    ports:
      - 3366:3366
    expose:
      - '3366'
    volumes:    
      - ./db_mysql:/docker-entrypoint-initdb.d/
      - db_mysql:/var/lib/mysql
    networks:
      - network      
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

networks:  
  network:    
    driver: bridge

volumes:          
  db_mysql:
