version: '3.5'

services:
  db_mysql:
    container_name: 'deployment_db_mysql'
    image: mysql:8.0.27  # Updated to MySQL 8
    environment:      
      MYSQL_DATABASE: 'urlshortener'              
      MYSQL_USER: 'urluser'      
      MYSQL_PASSWORD: "Dharani@2004"  # Quoted
      MYSQL_ROOT_PASSWORD: "Dharani@2004"  # Quoted
    ports:
      - 3366:3306  # Map host 3366 → container 3306
    volumes:    
      - db_mysql:/var/lib/mysql
    networks:
      - network      

networks:  
  network:    
    driver: bridge

volumes:          
  db_mysql:
